### ISSUE TITLE
SequelizeEagerLoadingError: user_roles is not associated to users!

### ISSUE THREAD

**Issue by AryanChothani** [rtoal/community#1]
I am creating a role base app by puting this project idle but i am geting this error

      SequelizeEagerLoadingError: user_roles is not associated to users!
       at Function._getIncludedAssociation (d:\demos\New folder\node_modules\sequelize\lib\model.js:717:13)
       at Function._validateIncludedElement (d:\demos\New folder\node_modules\sequelize\lib\model.js:621:53)
       at d:\demos\New folder\node_modules\sequelize\lib\model.js:516:37
       at Array.map (<anonymous>)
       at Function._validateIncludedElements (d:\demos\New folder\node_modules\sequelize\lib\model.js:511:39)
       at d:\demos\New folder\node_modules\sequelize\lib\model.js:1728:14
       at clsBind (d:\demos\New folder\node_modules\cls-hooked\context.js:172:17)
       at tryCatcher (d:\demos\New folder\node_modules\bluebird\js\release\util.js:16:23)
       at Promise._settlePromiseFromHandler (d:\demos\New folder\node_modules\bluebird\js\release\promise.js:547:31)
       at Promise._settlePromise (d:\demos\New folder\node_modules\bluebird\js\release\promise.js:604:18)
       at Promise._settlePromise0 (d:\demos\New folder\node_modules\bluebird\js\release\promise.js:649:10)
       at Promise._settlePromises (d:\demos\New folder\node_modules\bluebird\js\release\promise.js:729:18)
       at _drainQueueStep (d:\demos\New folder\node_modules\bluebird\js\release\async.js:93:12)
       at _drainQueue (d:\demos\New folder\node_modules\bluebird\js\release\async.js:86:9)
       at Async._drainQueues (d:\demos\New folder\node_modules\bluebird\js\release\async.js:102:5)
       at Immediate.Async.drainQueues [as _onImmediate] (d:\demos\New folder\node_modules\bluebird\js\release\async.js:15:14)
       at processImmediate (<node_internals>/internal/timers.js:456:21)
       at process.callbackTrampoline (internal/async_hooks.js:120:14) {name: 'SequelizeEagerLoadingError', error@context: {…}, 
       stack: 'SequelizeEagerLoadingError: user_roles is not…ckTrampoline (internal/async_hooks.js:120:14)', message: 'user_roles is 
        not associated to users!'}
         apis/authentication_api.js:147

this is my `users.model.js` code

          

    module.exports = function (sequelize, DataTypes) {

    const users = sequelize.define('users', {
        id: {
            type: DataTypes.INTEGER(),
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        },
        first_name: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        last_name: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        email: {
            type: DataTypes.TEXT,
            allowNull: false
        },
        password: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        address: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        city_id: {
            type: DataTypes.INTEGER(),
            allowNull: true
        },
        state_id: {
            type: DataTypes.INTEGER(),
            allowNull: true
        },
        country_id: {
            type: DataTypes.INTEGER(),
            allowNull: true
        },
        role_id: {
            type: DataTypes.INTEGER(),
            allowNull: true
        },
        user_type: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        phone: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        img: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        signup_token: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        organization_id: {
            type: DataTypes.INTEGER,
            allowNull: true
        },
        is_confirmed: {
            type: DataTypes.BOOLEAN,
            allowNull: true
        },
        is_active: {
            type: DataTypes.BOOLEAN,
            allowNull: true
        },
        created_at: {
            type: DataTypes.DATE,
            allowNull: true
        },
        updated_at: {
            type: DataTypes.DATE,
            allowNull: true
        }
        });

         return users
         };

this is `user_roles.model.js`

     module.exports = function (sequelize, DataTypes) {
  
         const user_roles = sequelize.define('user_roles', {
             user_id: {
                type: DataTypes.INTEGER,
                allowNull: true,
                 references: {
                    model: 'users',
                    key: 'id',
                  },
            },
            role_id: {
                 type: DataTypes.INTEGER,
                 allowNull: true,
                 references: {
                  model: 'roles',
                  key: 'id',
               },
             }
         });
        return user_roles
      };

this is assoctiations 

       db.roles.belongsToMany(db.users, {
           through: "user_roles",
           foreignKey: "role_id",
           otherKey: "user_id"
       });
       db.users.belongsToMany(db.roles, {
            through: "user_roles",
            foreignKey: "user_id",
            otherKey: "role_id"
       });

this api where i am getting errror

       verifyOTP: async (req, res) => {

        if (req.body.body_encrypted) {
            let original_data = helpers.decrypt(req.body.body_encrypted);
            req.body = original_data;
        }

        if (!req.headers.session_token || !req.body.otp) {
            return res.status(401).json(error.MANDATORY_FIELDS);
        }

        sequelize.sequelize.transaction(async (t1) => {

            let token = await sequelize.verify_otp.findOne({
                where: {
                    session_token: req.headers.session_token,
                    is_active: true,
                }
            });

            if (!token) {
                return res.status(401).send(error.SESSION_TOKEN_NOT_VALID);
            }

            token = token.get();
            var currentDate = new Date(new Date().toUTCString());
            var otpGenerateDate = new Date(new Date(token.otp_generate_time).toUTCString());
            const dateDifference = helpers.dateDifference(currentDate, otpGenerateDate);

            if (token.otp !== parseInt(req.body.otp)) {
                return res.status(401).send(error.VERIFICATION_FAILURE);
            }
             else if (dateDifference.seconds() > 600) {
                 return res.status(200).send(error.OTP_EXPIRED);
             }
            else {
                await sequelize.verify_otp.update(
                    { is_active: false },
                    {
                       where: { email: token.email }
                    });

                let user = await sequelize.users.findOne({
                    where: {
                        email: token.email,
                        is_active: true,
                        is_confirmed: true
                    },attribute: {
                        excluce: ["password", "signup_token"]
                    },
                    include: [
                        {
                            model : sequelize.user_roles,
                            include:[sequelize.roles]
                        }
                    ]
                });

                let role = await sequelize.roles.findOne({
                    where: {
                        id: user.role_id
                    }
                })

                if (user)
                delete user.password;
                user = user.get();
                role = role.get();
                const tokenOriginal = helpers.generateUserToken(user.id, user.email, user.role_id, role.name,user.user_type, 
     user.first_name, user.last_name, user.phone, user.city_id, user.state_id, user.country_id, user.organization_id);

                var result = error.OK;
                result.token = tokenOriginal;
                console.log(JSON.stringify(user))
                return res.status(200).send(result);
                
            }
        }).catch(function (err) {
            console.log(err)
            return res.status(500).send(error.SERVER_ERROR);
        });
    }

**Comment by AryanChothani** [comment]
i got my error

            include: [
                    {
                        model : sequelize.roles
                     }
                ]

thank you your notes helped me alot
